{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yagami.fullname" . }}
  labels:
    {{- include "yagami.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "yagami.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.observability.serviceMonitor.interval }}
      {{- with .Values.observability.serviceMonitor.bearerTokenSecret.name }}
      authorization:
        type: Bearer
        credentials:
          name: {{ . | quote }}
          key: {{ $.Values.observability.serviceMonitor.bearerTokenSecret.key | quote }}
      {{- end }}
{{- end }}
